version: '3.8'
services:
    php-apache:
        container_name: php-apache
        image: php:8.2.6-apache
        build :
          context: .
          dockerfile: ./php/Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - "80:80"
    db:
        container_name: db-mysql
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_DATABASE: "db_crud"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "oke123"
        volumes:
          - ./dbase:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
    phpmyadmin:
      container_name: db-phpmyadmin
      image: phpmyadmin/phpmyadmin
      ports:
        - "8080:80"
      restart: always
      environment:
        PMA_HOST: db
      depends_on:
        - db
    web:
      container_name: web-nginx
      image: nginx
      ports:
      - "8000:80"
      depends_on:
        - db
      volumes:
        - ./nginx/src:/var/www/html/
      